#!/bin/bash

working_directory=$(pwd)
echo $working_directory

current_branch=$(git symbolic-ref --short HEAD)

git submodule update --init --recursive

grep -E '\[submodule "([^"]+)"\]' .gitmodules | while read -r line; do
    submodule_name=$(echo "$line" | awk -F'"' '/\[submodule/ {print $2}')

    echo "Debugging1 $line"
    echo "Debugging2 $submodule_name"
    echo "Debugging3 $current_branch"

    if [ -e "$submodule_name" ]; then
        cd "$submodule_name"

        git fetch origin "$current_branch"
        git checkout "$current_branch"
        git pull origin "$current_branch"

        cd $working_directory
    else
        echo "$submodule_name does not exist. Skipping submodule update."
    fi
done