#!/bin/bash

grep -E '\[submodule "([^"]+)"\]' .gitmodules | while read -r line; do
    # submodule_name=$(echo "$line" | sed -n 's/\[submodule "\(.*\)"\]/\1/p')

    submodule_name=$(echo "$line" | awk -F'"' '/\[submodule/ {print $2}')

    echo "ihuu0 $line"
    echo "ihuu $submodule_name"

    # if [ -e "$submodule_name" ]; then
    #     cd "$submodule_name"

    #     git fetch origin "$current_branch"
    #     git checkout "$current_branch"
    #     git pull origin "$current_branch"

    #     cd ..
    # fi
done